### ISSUE TITLE
[Problem] String consts

### ISSUE THREAD

**Issue by SugarBarrel** [SugarBarrel/RogueLibs#36]
Currently, `Vanilla_____` classes don't have all of the identifiers. For instance, `VanillaTraits` doesn't have a lot of + versions of traits.

**Comment by Freiling87** [comment]
I've been gradually expanding these lists, there are more complete versions in my mod. I will try to get around to submitting them as a pull request.

**Comment by SugarBarrel** [comment]
RogueLibs v3 will no longer be updated. Reopen the issue if the issue persists in v4+.
