### ISSUE TITLE
[Feature] Custom Interactions

### ISSUE THREAD

**Issue by SugarBarrel** [SugarBarrel/RogueLibs#50]
### Describe the problem

Adding custom interactions with objects is really complicated, especially if you want your interactions to be compatible with other mods' interactions. Also the methods are really inconsistent, and sometimes you might just need a couple of postfix-patches, and sometimes even a transpiler.

### Describe the solution

Implement custom interactions in RLv3 via hooks.

`InteractionModel` will manage the interactions for a `PlayfieldObject`. It will gather actions from a global list of `IInteractionProvider`s, sort and filter them and then display the menu with buttons. The base class is abstract, and all actual instances derive from `InteractionModel<T>`.

`IInteractionProvider` will create `Interaction`s, bind them to the current object and pass them to the manager. They are stored in `RogueInteractions.Providers`.

`Interaction` is a base class for managing the button-action itself: its name, price, extra information and etc. There will be two default implementations of that class - `CustomInteraction`, exposed for mod developers, and `SimpleInteraction` that uses a simplified syntax with delegates (see `SimpleInteractionProvider`).

### How would that work?

Here's how vanilla Barbecue interactions could be defined:

```cs
// All of the used delegates must be static to avoid referencing outdated variables.
// Properties that should not be accessed should throw an InvalidOperationException.

// This method uses the simplified syntax, using SimpleInteractionProvider<Barbecue>
RogueInteractions.CreateProvider<Barbecue>(static h => // 'h' is for 'handler'
{
    if (h.Helper.interactingFar) return; // No buttons will be added

    if (h.Object.burntOut)
    {
        // Set what will happen, if the interaction is unsuccessful.
        // Interaction is unsuccessful only if there are no available buttons or if one
        // of the providers stopped the interaction forcefully (`h.StopInteraction()`).
        h.SetStopCallback(static m => m.Agent.SayDialogue("BarbecueBurntOut"));
        // Use it to tell the player why the operation was unsuccessful.
    }
    else if (h.Object.ora.hasParticleEffect)
    {
        if (h.Agent.inventory.HasItem(VanillaItems.Fud))
        {
            // Creates a button, that, when clicked, will call the specified delegate.
            h.AddButton("GrillFud", static m => // 'm' is for 'model'
            {
                m.Object.StartCoroutine(m.Object.Operating(m.Agent, null, 2f, true, "Grilling"));
            });
        }
        else h.SetStopCallback(static m => m.Agent.SayDialogue("CantGrillFud"));
    }
    else
    {
        if (h.Agent.inventory.HasItem(VanillaItems.CigaretteLighter))
        {
            h.AddButton("LightBarbecue", static m =>
            {
                m.Object.StartFireInObject();
                m.StopInteraction();
            });
        }
        else h.SetStopCallback(static m => m.Agent.SayDialogue("CantOperateBarbecue"));
    }
});
```

### Open Questions

Should vanilla interactions derive from a separate class `VanillaInteraction` instead? If so, then should all vanilla interactions be rewritten as individual classes, or should a simplified syntax be used?

**Comment by Abbysssal** [comment]
When I implement the basics of that new system, I'll create an issue with the list of all interactable objects to rewrite the interactions for.

**Comment by SugarBarrel** [comment]
All vanilla interactions are rewritten and all vanilla objects are now interactable.
There's just one issue with the lockdown walls - the highlight doesn't work on them. I'll create a separate issue for that.
