### ISSUE TITLE
Collapsible Groups for ListBox items

### ISSUE THREAD

**Issue by Freiling87** [SugarBarrel/RogueLibs#58]
### Describe the problem

Mod content additions will make the player's List Boxes (for Mutators, Traits, etc.) crowded and difficult to traverse.

### Describe the solution

Create a system that allows the modder to assign their content to Menu Groups. If RogueLibs detects a Menu Group, it will create a collapsible/expandable menu group. The ones used in AToM were ideal.

**Comment by SugarBarrel** [comment]
RogueLibs v3 will no longer be updated. Reopen the issue if the issue persists in v4+.
