### ISSUE TITLE
[Bug] Hackable NPCs do not have hacking options when you have Speed Coder

### ISSUE THREAD

**Issue by TheShadowHat** [SugarBarrel/RogueLibs#74]
### Describe the bug

When hacking a hackable NPC when you have the Speed Coder trait, none of the hacking options show up. The camera pans to the NPC as normal, but no options show up.

Same applies when playing as an SSA Hacker.

There's no option for it in the "What version of the game are you running?" section so I'm gonna say here it's latest vanilla SOR version (v98)

### Expected behavior

When the NPC is hacked, the usual hacking options show up.

### What operating system are you on?

Windows 64-bit

### What version of the game are you running?

v97

### What version of RogueLibs are you running?

v3.6.9

**Comment by SugarBarrel** [comment]
Huh, I thought I already fixed this bug :thinking:. Must have been a dream.
It is now fixed in [v4.0.0-beta.6](https://github.com/SugarBarrel/RogueLibs/releases/tag/v4.0.0-beta.6) (commit 2b5b2400c3774bee5b2f7bac42ad8a34e8e5cd4a).
